junit 4 assignment
jasleenwahi/junitassignment pull request #1
Opened 2023-04-08 09:48 UTC by jasleenwahi

2023-04-09 12:56 UTC, anup0060 requested changes

2023-04-09 12:56 UTC, anup0060 commented on junit4assignment/src/main/java/org/example/StringUtils.java
> +    public Boolean isEmpty1(String stringToCheck)
poor method naming

2023-04-09 12:56 UTC, anup0060 commented on junit4assignment/src/test/java/org/example/StringUtilsTest.java
> +    public void testReverseShouldReturnReverse_test1()
_test1 _test2 , why all methods with these suffixes 

testReverse_givenExpectedInput -- like this, we need to have the name that reflects scenario as suffix.

2023-04-11 13:28 UTC, jasleenwahi reviewed
changes made requested by you, thank you for the review it helped me learn a lot.

2023-04-12 14:23 UTC, anup0060 requested changes

2023-04-12 14:23 UTC, anup0060 commented on junit4assignment/src/test/java/org/example/StringUtilsTest.java
> +    public void testReverse_The_String_With_NonEmpty_String()
see review comment of junit 5 , apply here - naming convention

2023-04-12 16:41 UTC, jasleenwahi reviewed
made all the required changes, thankyou for the review sir

2023-04-12 17:41 UTC, jasleenwahi reviewed
Changed the convention, thank you for making me understand better naming convention

2023-04-12 17:44 UTC, anup0060 approved these changes

2023-04-12 17:44 UTC, merged