junit 5 assignment
jasleenwahi/junitassignment pull request #2
Opened 2023-04-08 11:07 UTC by jasleenwahi

please review my junit 5 assignment

2023-04-09 12:58 UTC, anup0060 requested changes

2023-04-09 12:58 UTC, anup0060 commented on junit5assignment/src/test/java/com/knoldus/PersonTest.java
> +    public void nameTest(){
not all scenarios covered 

and method naming not good - use something like - test<ActualMethodName>_given<Input> ex - testName_givenNameNull

2023-04-11 13:19 UTC, jasleenwahi reviewed
I have made the changes suggested by you, thank you for the feedback sir it made me learn and improve my code.

2023-04-11 16:19 UTC, jasleenwahi reviewed
Changes made, thank you for the review sir it helped me lot in learning.

2023-04-12 14:22 UTC, anup0060 requested changes

2023-04-12 14:22 UTC, anup0060 commented on junit5assignment/src/test/java/com/knoldus/PersonTest.java
> +    void testGetName_With_Non_Null_Value() {
_given<>_should<>

_givenNotNull_shouldReturnNotNull

2023-04-12 16:28 UTC, jasleenwahi reviewed
Made the required changes, thankyou for the review sir.

2023-04-12 17:40 UTC, jasleenwahi reviewed
Changed the convention, thank you for making me understand better naming convention

2023-04-12 17:46 UTC, anup0060 approved these changes

2023-04-12 17:46 UTC, merged